routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');

Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/validate-login', 'Auth\LoginController@validateLogin');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Admin routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth.isAdmin'], function () {
    // Airports
    Route::get('airports/import', 'Airport\AirportAdminController@import')->name('admin.airports.import');
    Route::resource('airports', 'Airport\AirportAdminController');

    // AirportLinks
    Route::resource('airportLinks', 'AirportLink\AirportLinkAdminController')->except(['show']);

    // Faq
    Route::resource('faq', 'Faq\FaqAdminController')->except('show');
    Route::patch('faq/{faq}/toggle-event/{event}', 'Faq\FaqAdminController@toggleEvent')->name('faq.toggleEvent');

    // Event
    Route::resource('events', 'Event\EventAdminController');
    Route::get('{event}/email', 'Event\EventAdminController@sendEmailForm')->name('events.email.form');
    Route::patch('{event}/email', 'Event\EventAdminController@sendEmail')->name('events.email');
    Route::patch('{event}/email_final',
        'Event\EventAdminController@sendFinalInformationMail')->name('events.email.final');

    // Booking
    Route::resource('bookings', 'Booking\BookingAdminController')->except(['index', 'show']);
    Route::get('{event}/bookings/export/{vacc?}', 'Booking\BookingAdminController@export')->name('bookings.export');
    Route::get('{event}/bookings/create/{bulk?}', 'Booking\BookingAdminController@create')->name('bookings.create');
    Route::get('{event}/bookings/import', 'Booking\BookingAdminController@importForm')->name('bookings.importForm');
    Route::put('{event}/bookings/import', 'Booking\BookingAdminController@import')->name('bookings.import');
    Route::get('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssignForm')->name('bookings.autoAssignForm');
    Route::patch('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssign')->name('bookings.autoAssign');
    Route::get('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssignForm')->name('bookings.routeAssignForm');
    Route::patch('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssign')->name('bookings.routeAssign');
});

Route::resource('bookings', 'Booking\BookingController')->except(['create', 'edit', 'store', 'destroy']);
Route::get('/{event}/bookings/{filter?}', 'Booking\BookingController@index')->name('bookings.event.index');
Route::get('/bookings/{booking}/edit', 'Booking\BookingController@edit')
    ->middleware('auth.isLoggedIn')->name('bookings.edit');
Route::patch('/bookings/{booking}/cancel', 'Booking\BookingController@cancel')->name('bookings.cancel');

// Keeping this here for a while to prevent some 404's should people access /booking directly
Route::redirect('/booking', route('bookings.index'), 301);

Route::get('faq', 'Faq\FaqController')->name('faq');

Route::get('{event}', 'Event\EventController')->name('events.show');

Route::middleware('auth.isLoggedIn')->group(function () {
    Route::prefix('user')->name('user.')
        ->group(function () {
            Route::get('settings', 'User\UserController@showSettingsForm')->name('settings');
            Route::patch('settings', 'User\UserController@saveSettings')->name('saveSettings');
        });
});

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * App\Models\Faq
 *
 * @property int $id
 * @property bool $is_online
 * @property string $question
 * @property string $answer
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\Activitylog\Models\Activity[] $activities
 * @property-read int|null $activities_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Event[] $events
 * @property-read int|null $events_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereAnswer($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereIsOnline($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereQuestion($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Faq whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Faq extends Model
{
    use LogsActivity;

    protected $guarded = ['id'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_online' => 'boolean',
    ];

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    public function events()
    {
        return $this->belongsToMany(Event::class);
    }
}

app/Http/Controllers/Faq/FaqAdminController.php
<?php

namespace App\Http\Controllers\Faq;

use App\Http\Controllers\AdminController;
use App\Http\Requests\Faq\Admin\StoreFaq;
use App\Http\Requests\Faq\Admin\UpdateFaq;
use App\Models\Event;
use App\Models\Faq;
use App\Policies\FaqPolicy;

class FaqAdminController extends AdminController
{

    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->authorizeResource(FaqPolicy::class, 'faq');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faqs = Faq::withCount('events')->paginate();
        return view('faq.admin.overview', compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $faq = new Faq();
        return view('faq.admin.form', compact('faq'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreFaq  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFaq $request)
    {
        $faq = Faq::create($request->validated());
        flashMessage('success', 'Done', 'Question has been added!');
        return redirect(route('admin.faq.edit', $faq));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function edit(Faq $faq)
    {
        $events = Event::where('endEvent', '>', now())
            ->orderBy('startEvent', 'desc')
            ->get();

        return view('faq.admin.form', compact('faq', 'events'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateFaq  $request
     * @param  Faq  $faq
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFaq $request, Faq $faq)
    {
        $faq->update($request->validated());
        flashMessage('success', 'Done', 'Question has been updated!');
        return redirect(route('admin.faq.edit', $faq));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Faq  $faq
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Faq $faq)
    {
        $faq->delete();
        flashMessage('success', 'Done', 'Question has been removed!');
        return redirect(route('admin.faq.index'));
    }

    /**
     * Link or unlink a event to a FAQ
     *
     * @param  Faq  $faq
     * @param  Event  $event
     * @return \Illuminate\Http\RedirectResponse
     */
    public function toggleEvent(Faq $faq, Event $event)
    {
        if ($faq->events()->where('event_id', $event->id)->get()->isNotEmpty()) {
            $faq->events()->detach($event->id);
            flashMessage('success', 'Event unlinked', 'Event has been unlinked to this FAQ');
        } else {
            $faq->events()->attach($event->id);
            flashMessage('success', 'Event linked', 'Event has been linked to this FAQ');
        }
        return back();
    }
}

app/Http/Controllers/Faq/FaqController.php
<?php

namespace App\Http\Controllers\Faq;

use App\Http\Controllers\Controller;
use App\Models\Faq;
use Illuminate\Http\Request;

class FaqController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $faqs = Faq::doesntHave('events')
            ->whereIsOnline(true)
            ->get();

        return view('faq.overview', compact('faqs'));
    }
}

resources/views/faq/admin/form.blade.php
@extends('layouts.app')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @include('layouts.alert')
    @push('scripts')
        <script>
            $('.unlik-event').on('click', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Are you sure',
                    text: 'Are you sure you want to unlink this event?',
                    icon: 'warning',
                    showCancelButton: true,
                }).then((result) => {
                    if (result.value) {
                        Swal.fire('Unlinking event...');
                        Swal.showLoading();
                        $(this).closest('form').submit();
                    }
                });
            });
        </script>
    @endpush
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $faq->id ? 'Edit' : 'Add new' }} FAQ</div>

                <div class="card-body">
                    <form method="POST"
                          action="{{ $faq->id ? route('admin.faq.update', $faq) : route('admin.faq.store') }}">
                        @csrf
                        @if($faq->id)
                            @method('PATCH')
                        @endif

                        {{--Online--}}
                        <div class="form-group row">
                            <label for="is_online" class="col-md-4 col-form-label text-md-right"> Online?</label>

                            <div class="col-md-6">
                                <div class="custom-control custom-control-inline custom-radio">
                                    <input type="radio" value="0" id="is_online0" name="is_online"
                                           class="custom-control-input" {{ old('is_online', $faq->is_online) == 0 ? 'checked' : '' }}>
                                    <label class="custom-control-label" for="is_online0">No</label>
                                </div>
                                <div class="custom-control custom-control-inline custom-radio">
                                    <input type="radio" value="1" id="is_online1" name="is_online"
                                           class="custom-control-input" {{ old('is_online', $faq->is_online) == 1 ? 'checked' : '' }}>
                                    <label class="custom-control-label" for="is_online1">Yes</label>
                                </div>

                                @if ($errors->has('is_online'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('is_online') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Question--}}
                        <div class="form-group row">
                            <label for="question" class="col-md-4 col-form-label text-md-right"> Question</label>

                            <div class="col-md-6">
                                <input id="question" type="text"
                                       class="form-control{{ $errors->has('question') ? ' is-invalid' : '' }}"
                                       name="question"
                                       value="{{ old('question', $faq->question) }}" required>

                                @if ($errors->has('question'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('question') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Answer--}}
                        <div class="form-group row">
                            <label for="answer" class="col-md-4 col-form-label text-md-right"> Answer</label>

                            <textarea id="description" name="answer"
                                      rows="10">{!! html_entity_decode(old('answer', $faq->answer)) !!}</textarea>

                            @if ($errors->has('answer'))
                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('answer') }}</strong>
                                    </span>
                            @endif
                        </div>

                        {{--Add/Edit--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    @if($faq->id)
                                        <i class="fa fa-check"></i> Edit
                                    @else
                                        <i class="fa fa-plus"></i> Add
                                    @endif
                                </button>
                            </div>
                        </div>
                    </form>
                </div>

                @if($faq->id)
                    <div class="card-header">Related events</div>
                    @if($events)
                        <div class="card-body">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="row">Name</th>
                                    <th scope="row">Actions</th>
                                </tr>
                                </thead>
                                @foreach($events as $event)
                                    <tr>
                                        <td>{{ $event->name }} [{{ $event->startEvent->format('d-m-Y') }}]</td>
                                        <td>
                                            <form
                                                action="{{ route('admin.faq.toggleEvent', ['faq' => $faq, 'event' => $event]) }}"
                                                method="post">
                                                @csrf
                                                @method('PATCH')

                                                @if($faq->events()->where('event_id', $event->id)->first())
                                                    <button class="btn btn-danger unlink-event">Unlink event</button>
                                                @else
                                                    <button class="btn btn-success">Link event</button>
                                                @endif
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    @endif
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/faq/admin/overview.blade.php
@extends('layouts.app')

@section('content')
    <h3>FAQ Overview</h3>
    <hr>
    @include('layouts.alert')
    @push('scripts')
        <script>
            $('.delete-faq').on('click', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Are you sure',
                    text: 'Are you sure you want to remove this faq?',
                    icon: 'warning',
                    showCancelButton: true,
                }).then((result) => {
                    if (result.value) {
                        Swal.fire('Deleting faq...');
                        Swal.showLoading();
                        $(this).closest('form').submit();
                    }
                });
            });
        </script>
    @endpush
    <p>
        <a href="{{ route('admin.faq.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add new FAQ</a>
    </p>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="row">ID</th>
            <th scope="row">Question</th>
            <th scope="row">Linked?</th>
            <th scope="row" colspan="2">Actions</th>
        </tr>
        </thead>
        @forelse($faqs as $faq)
            <tr>
                <td>{{ $faq->id }}</td>
                <td>{{ $faq->question }}</td>
                <td>{{ $faq->events_count ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ route('admin.faq.edit', $faq) }}">
                        <button class="btn btn-primary">
                            <i class="fa fa-edit"></i> Edit FAQ
                        </button>
                    </a>
                </td>
                <td>
                    <form action="{{ route('admin.faq.destroy', $faq) }}" method="post">
                        @method('DELETE')
                        <button class="btn btn-danger delete-faq"><i class="fa fa-trash"></i> Remove FAQ</button>
                        @csrf
                    </form>
                </td>
            </tr>
        @empty
            @php
                flashMessage('warning', 'No faq\'s found', 'No faq\'s are in the system, consider adding one, using the button above');
            @endphp
            @include('layouts.alert')
        @endforelse
        {{ $faqs->links() }}
    </table>
    {{ $faqs->links() }}
@endsection