routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');

Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/validate-login', 'Auth\LoginController@validateLogin');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Admin routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth.isAdmin'], function () {
    // Airports
    Route::get('airports/import', 'Airport\AirportAdminController@import')->name('admin.airports.import');
    Route::resource('airports', 'Airport\AirportAdminController');

    // AirportLinks
    Route::resource('airportLinks', 'AirportLink\AirportLinkAdminController')->except(['show']);

    // Faq
    Route::resource('faq', 'Faq\FaqAdminController')->except('show');
    Route::patch('faq/{faq}/toggle-event/{event}', 'Faq\FaqAdminController@toggleEvent')->name('faq.toggleEvent');

    // Event
    Route::resource('events', 'Event\EventAdminController');
    Route::get('{event}/email', 'Event\EventAdminController@sendEmailForm')->name('events.email.form');
    Route::patch('{event}/email', 'Event\EventAdminController@sendEmail')->name('events.email');
    Route::patch('{event}/email_final',
        'Event\EventAdminController@sendFinalInformationMail')->name('events.email.final');

    // Booking
    Route::resource('bookings', 'Booking\BookingAdminController')->except(['index', 'show']);
    Route::get('{event}/bookings/export/{vacc?}', 'Booking\BookingAdminController@export')->name('bookings.export');
    Route::get('{event}/bookings/create/{bulk?}', 'Booking\BookingAdminController@create')->name('bookings.create');
    Route::get('{event}/bookings/import', 'Booking\BookingAdminController@importForm')->name('bookings.importForm');
    Route::put('{event}/bookings/import', 'Booking\BookingAdminController@import')->name('bookings.import');
    Route::get('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssignForm')->name('bookings.autoAssignForm');
    Route::patch('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssign')->name('bookings.autoAssign');
    Route::get('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssignForm')->name('bookings.routeAssignForm');
    Route::patch('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssign')->name('bookings.routeAssign');
});

Route::resource('bookings', 'Booking\BookingController')->except(['create', 'edit', 'store', 'destroy']);
Route::get('/{event}/bookings/{filter?}', 'Booking\BookingController@index')->name('bookings.event.index');
Route::get('/bookings/{booking}/edit', 'Booking\BookingController@edit')
    ->middleware('auth.isLoggedIn')->name('bookings.edit');
Route::patch('/bookings/{booking}/cancel', 'Booking\BookingController@cancel')->name('bookings.cancel');

// Keeping this here for a while to prevent some 404's should people access /booking directly
Route::redirect('/booking', route('bookings.index'), 301);

Route::get('faq', 'Faq\FaqController')->name('faq');

Route::get('{event}', 'Event\EventController')->name('events.show');

Route::middleware('auth.isLoggedIn')->group(function () {
    Route::prefix('user')->name('user.')
        ->group(function () {
            Route::get('settings', 'User\UserController@showSettingsForm')->name('settings');
            Route::patch('settings', 'User\UserController@saveSettings')->name('saveSettings');
        });
});

app/Models/AirportLink.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * App\Models\AirportLink
 *
 * @property int $id
 * @property int $airport_id
 * @property int $airportLinkType_id
 * @property string|null $name
 * @property string $url
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\Activitylog\Models\Activity[] $activities
 * @property-read int|null $activities_count
 * @property-read \App\Models\Airport $airport
 * @property-read \App\Models\AirportLinkType $type
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereAirportId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereAirportLinkTypeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLink whereUrl($value)
 * @mixin \Eloquent
 */
class AirportLink extends Model
{
    use LogsActivity;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    public function airport()
    {
        return $this->hasOne(Airport::class, 'id', 'airport_id');
    }

    public function type()
    {
        return $this->hasOne(AirportLinkType::class, 'id', 'airportLinkType_id');
    }
}

app/Models/AirportLinkType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * App\Models\AirportLinkType
 *
 * @property int $id
 * @property string $name
 * @property string|null $class
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\Activitylog\Models\Activity[] $activities
 * @property-read int|null $activities_count
 * @property-read \App\Models\AirportLink $links
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType whereClass($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\AirportLinkType whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class AirportLinkType extends Model
{
    use LogsActivity;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    public function links()
    {
        return $this->belongsTo(AirportLink::class, 'id');
    }
}

app/Http/Controllers/AirportLink/AirportLinkAdminController.php
<?php

namespace App\Http\Controllers\AirportLink;

use App\Http\Controllers\AdminController;
use App\Http\Requests\AirportLink\Admin\StoreAirportLink;
use App\Http\Requests\AirportLink\Admin\UpdateAirportLink;
use App\Models\Airport;
use App\Models\AirportLink;
use App\Models\AirportLinkType;
use App\Policies\AirportLinkPolicy;

class AirportLinkAdminController extends AdminController
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->authorizeResource(AirportLinkPolicy::class, 'airportLink');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $airportLinks = AirportLink::orderBy('airport_id', 'asc')
            ->with(['airport', 'type'])
            ->paginate();
        return view('airportLink.admin.overview', compact('airportLinks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $airportLink = new AirportLink();
        $airportLinkTypes = AirportLinkType::all();
        $airports = Airport::orderBy('icao')->get();
        return view('airportLink.admin.form', compact('airportLink', 'airportLinkTypes', 'airports'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreAirportLink  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAirportLink $request)
    {
        $airportLink = AirportLink::create($request->validated());
        flashMessage('success', 'Done',
            $airportLink->type->name.' item has been added for '.$airportLink->airport->name.' ['.$airportLink->airport->icao.' | '.$airportLink->airport->iata.']');
        return redirect(route('admin.airports.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\AirportLink  $airportLink
     * @return \Illuminate\Http\Response
     */
    public function edit(AirportLink $airportLink)
    {
        $airportLinkTypes = AirportLinkType::all();
        return view('airportLink.admin.form', compact('airportLink', 'airportLinkTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateAirportLink  $request
     * @param  \App\Models\AirportLink  $airportLink
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAirportLink $request, AirportLink $airportLink)
    {
        $airportLink->update($request->validated());
        flashMessage('success', 'Done', 'Link has been updated');
        return redirect(route('admin.airportLinks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\AirportLink  $airportLink
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(AirportLink $airportLink)
    {
        $airportLink->delete();
        flashMessage('success', 'Airport link deleted', 'Airport link has been deleted');
        return back();
    }
}

resources/views/airportLink/admin/form.blade.php
@extends('layouts.app')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $airportLink->id ? 'Edit' : 'Add new' }} Airport Link</div>

                <div class="card-body">
                    <form method="POST"
                          action="{{ $airportLink->id ? route('admin.airportLinks.update', $airportLink) : route('admin.airportLinks.store') }}">
                        @csrf
                        @if($airportLink->id)
                            @method('PATCH')
                        @endif
                        {{--Type--}}
                        <div class="form-group row">
                            <label for="airportLinkType_id" class="col-md-4 col-form-label text-md-right">Type</label>

                            <div class="col-md-6">
                                <select
                                    class="custom-select form-control{{ $errors->has('type') ? ' is-invalid' : '' }}"
                                    name="airportLinkType_id">
                                    <option value="">Choose type...</option>
                                    @if($airportLink->id)
                                        @foreach($airportLinkTypes as $airportLinkType)
                                            <option
                                                value="{{ $airportLinkType->id }}" {{ old('airportLinkType_id', $airportLink->type->id) == $airportLinkType->id ? 'selected' : '' }}>{{ $airportLinkType->name }}</option>
                                        @endforeach
                                    @else
                                        @foreach($airportLinkTypes as $airportLinkType)
                                            <option
                                                value="{{ $airportLinkType->id }}" {{ old('airportLinkType_id') == $airportLinkType->id ? 'selected' : '' }}>{{ $airportLinkType->name }}</option>
                                        @endforeach
                                    @endif
                                </select>

                                @if ($errors->has('airportLinkType_id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('airportLinkType_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Airport--}}
                        <div class="form-group row">
                            <label for="icao_airport" class="col-md-4 col-form-label text-md-right">Airport</label>

                            <div class="col-md-6">
                                @if($airportLink->id)
                                    <div class="form-control form-control-plaintext">
                                        {{ $airportLink->airport->icao }} [{{ $airportLink->airport->name }}
                                        ({{ $airportLink->airport->iata }})]
                                    </div>
                                @else
                                    <select
                                        class="custom-select form-control{{ $errors->has('airport_id') ? ' is-invalid' : '' }}"
                                        name="airport_id">
                                        <option value="">Choose an airport...</option>
                                        @foreach($airports as $airport)
                                            <option
                                                value="{{ $airport->id }}" {{ old('airport_id') == $airport->id ? 'selected' : '' }}>{{ $airport->icao }}
                                                [{{ $airport->name }} ({{ $airport->iata }})]
                                            </option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('airport_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('airport_id') }}</strong>
                                    </span>
                                    @endif
                                @endif
                            </div>
                        </div>

                        {{--Name--}}
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text"
                                       class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"
                                       value="{{ old('name', $airportLink->name) }}">

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--URL--}}
                        <div class="form-group row">
                            <label for="url" class="col-md-4 col-form-label text-md-right">URL</label>

                            <div class="col-md-6">
                                <input id="name" type="text"
                                       class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}" name="url"
                                       value="{{ old('url', $airportLink->url) }}" required>

                                @if ($errors->has('url'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('url') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Add/Edit--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    @if($airportLink->id)
                                        <i class="fa fa-check"></i> Edit
                                    @else
                                        <i class="fa fa-plus"></i> Add
                                    @endif
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/airportLink/admin/overview.blade.php
@extends('layouts.app')

@section('content')
    <h2>Airport Links Overview</h2>
    @include('layouts.alert')
    @push('scripts')
        <script>
            $('.delete-airportlink').on('click', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Are you sure',
                    text: 'Are you sure you want to remove this airport link?',
                    icon: 'warning',
                    showCancelButton: true,
                }).then((result) => {
                    if (result.value) {
                        Swal.fire('Deleting airport link...');
                        Swal.showLoading();
                        $(this).closest('form').submit();
                    }
                });
            });
        </script>
    @endpush
    <p>
        <a href=" {{ route('admin.airportLinks.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add new
            Airport
            Link</a>
    </p>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="row">Airport</th>
            <th scope="row">Type / Name</th>
            <th scope="row" colspan="2">Actions</th>
        </tr>
        </thead>
        @forelse($airportLinks as $airportLink)
            <tr>
                <td>
                    <a href="{{ route('admin.airports.show', $airportLink->airport) }}">{{ $airportLink->airport->name }}
                        [{{ $airportLink->airport->icao }} | {{ $airportLink->airport->iata }}]</a></td>
                <td><a href="{{ $airportLink->url }}">{{ $airportLink->name ?? $airportLink->type->name }}</a></td>
                <td>
                    <a href="{{ route('admin.airportLinks.edit', $airportLink) }}">
                        <button class="btn btn-primary">
                            <i class="fa fa-edit"></i> Edit Airport Link
                        </button>
                    </a>
                </td>
                <td>
                    <form action="{{ route('admin.airportLinks.destroy', $airportLink) }}" method="post">
                        @method('DELETE')
                        <button class="btn btn-danger delete-airportlink"><i class="fa fa-trash"></i> Remove Airport
                            Link
                        </button>
                        @csrf
                    </form>
                </td>
            </tr>
        @empty
            @php
                flashMessage('warning', 'No airport links found', 'No airport links are in the system, consider adding one, using the button above');
            @endphp
            @include('layouts.alert')
        @endforelse
        {{ $airportLinks->links() }}
    </table>
    {{ $airportLinks->links() }}
@endsection