routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');

Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/validate-login', 'Auth\LoginController@validateLogin');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Admin routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth.isAdmin'], function () {
    // Airports
    Route::get('airports/import', 'Airport\AirportAdminController@import')->name('admin.airports.import');
    Route::resource('airports', 'Airport\AirportAdminController');

    // AirportLinks
    Route::resource('airportLinks', 'AirportLink\AirportLinkAdminController')->except(['show']);

    // Faq
    Route::resource('faq', 'Faq\FaqAdminController')->except('show');
    Route::patch('faq/{faq}/toggle-event/{event}', 'Faq\FaqAdminController@toggleEvent')->name('faq.toggleEvent');

    // Event
    Route::resource('events', 'Event\EventAdminController');
    Route::get('{event}/email', 'Event\EventAdminController@sendEmailForm')->name('events.email.form');
    Route::patch('{event}/email', 'Event\EventAdminController@sendEmail')->name('events.email');
    Route::patch('{event}/email_final',
        'Event\EventAdminController@sendFinalInformationMail')->name('events.email.final');

    // Booking
    Route::resource('bookings', 'Booking\BookingAdminController')->except(['index', 'show']);
    Route::get('{event}/bookings/export/{vacc?}', 'Booking\BookingAdminController@export')->name('bookings.export');
    Route::get('{event}/bookings/create/{bulk?}', 'Booking\BookingAdminController@create')->name('bookings.create');
    Route::get('{event}/bookings/import', 'Booking\BookingAdminController@importForm')->name('bookings.importForm');
    Route::put('{event}/bookings/import', 'Booking\BookingAdminController@import')->name('bookings.import');
    Route::get('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssignForm')->name('bookings.autoAssignForm');
    Route::patch('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssign')->name('bookings.autoAssign');
    Route::get('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssignForm')->name('bookings.routeAssignForm');
    Route::patch('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssign')->name('bookings.routeAssign');
});

Route::resource('bookings', 'Booking\BookingController')->except(['create', 'edit', 'store', 'destroy']);
Route::get('/{event}/bookings/{filter?}', 'Booking\BookingController@index')->name('bookings.event.index');
Route::get('/bookings/{booking}/edit', 'Booking\BookingController@edit')
    ->middleware('auth.isLoggedIn')->name('bookings.edit');
Route::patch('/bookings/{booking}/cancel', 'Booking\BookingController@cancel')->name('bookings.cancel');

// Keeping this here for a while to prevent some 404's should people access /booking directly
Route::redirect('/booking', route('bookings.index'), 301);

Route::get('faq', 'Faq\FaqController')->name('faq');

Route::get('{event}', 'Event\EventController')->name('events.show');

Route::middleware('auth.isLoggedIn')->group(function () {
    Route::prefix('user')->name('user.')
        ->group(function () {
            Route::get('settings', 'User\UserController@showSettingsForm')->name('settings');
            Route::patch('settings', 'User\UserController@saveSettings')->name('saveSettings');
        });
});

app/Http/Controllers/Booking/BookingAdminController.php
<?php

namespace App\Http\Controllers\Booking;

use App\Enums\BookingStatus;
use App\Enums\EventType;
use App\Http\Controllers\AdminController;
use App\Http\Requests\Booking\Admin\AutoAssign;
use App\Http\Requests\Booking\Admin\ImportBookings;
use App\Http\Requests\Booking\Admin\RouteAssign;
use App\Http\Requests\Booking\Admin\StoreBooking;
use App\Http\Requests\Booking\Admin\UpdateBooking;
use App\Models\Airport;
use App\Models\Booking;
use App\Models\Event;
use App\Models\Flight;
use App\Notifications\BookingChanged;
use App\Notifications\BookingDeleted;
use App\Policies\BookingPolicy;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Rap2hpoutre\FastExcel\FastExcel;

class BookingAdminController extends AdminController
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->authorizeResource(BookingPolicy::class, 'booking');
    }

    /**
     * Show the form for creating new timeslots
     *
     * @param  Event  $event
     * @param  Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Event $event, Request $request)
    {
        $bulk = $request->bulk;
        $airports = Airport::orderBy('icao')->get();

        return view('booking.admin.create', compact('event', 'airports', 'bulk'));
    }

    /**
     * Store new timeslots in storage.
     *
     * @param  StoreBooking  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBooking $request)
    {
        $event = Event::whereKey($request->id)->first();
        if ($request->bulk) {
            $event_start = Carbon::createFromFormat('Y-m-d H:i',
                $event->startEvent->toDateString().' '.$request->start);
            $event_end = Carbon::createFromFormat('Y-m-d H:i', $event->endEvent->toDateString().' '.$request->end);
            $separation = $request->separation * 60;
            $count = 0;
            for (; $event_start <= $event_end; $event_start->addSeconds($separation)) {
                $time = $event_start->copy();
                if ($time->second >= 30) {
                    $time->addMinute();
                }
                $time->second = 0;

                if (!Flight::whereHas('booking', function ($query) use ($request) {
                    $query->where('event_id', $request->id);
                })->where([
                    'ctot' => $time,
                    'dep' => $request->dep,
                ])->first()) {
                    Booking::create([
                        'event_id' => $request->id,
                        'is_editable' => $request->is_editable,
                    ])->flights()->create([
                        'dep' => $request->dep,
                        'arr' => $request->arr,
                        'ctot' => $time,
                    ]);

                    $count++;
                }
            }
            flashMessage('success', 'Done', $count.' Slots have been created!');
        } else {
            $booking = new Booking([
                'is_editable' => $request->is_editable,
                'callsign' => $request->callsign,
                'acType' => $request->aircraft,
            ]);

            $booking->event()->associate($request->id)->save();
            $flightAttributes = [
                'dep' => $request->dep,
                'arr' => $request->arr,
                'route' => $request->route,
                'oceanicFL' => $request->oceanicFL,
            ];

            if ($request->ctot) {
                $flightAttributes['ctot'] = Carbon::createFromFormat('Y-m-d H:i',
                    $event->startEvent->toDateString().' '.$request->ctot);
            }

            if ($request->eta) {
                $flightAttributes['eta'] = Carbon::createFromFormat('Y-m-d H:i',
                    $event->startEvent->toDateString().' '.$request->eta);
            }

            $booking->flights()->create($flightAttributes);
            flashMessage('success', 'Done', 'Slot created');
        }
        return redirect(route('bookings.event.index', $event));
    }

    /**
     * Display the specified booking.
     *
     * @param  Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        return view('booking.show', compact('booking'));
    }

    /**
     * Show the form for editing the specified booking.
     * @param  Booking  $booking
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Booking $booking)
    {
        if ($booking->event->endEvent >= now()) {
            $airports = Airport::orderBy('icao')->get();
            $flight = $booking->flights()->first();
            return view('booking.admin.edit', compact('booking', 'airports', 'flight'));
        }
        flashMessage('danger', 'Nope!', 'You cannot edit a booking after the event ended');
        return back();
    }

    /**
     * Updates booking.
     *
     * @param  UpdateBooking  $request
     * @param  Booking  $booking
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UpdateBooking $request, Booking $booking)
    {
        $shouldSendEmail = false;
        if (!empty($booking->user) && $request->notify_user) {
            $shouldSendEmail = true;
        }
        /* @var Flight $flight */
        $flight = $booking->flights()->first();
        $booking->fill([
            'is_editable' => $request->is_editable,
            'callsign' => $request->callsign,
            'acType' => $request->aircraft,
            'final_information_email_sent_at' => null
        ]);

        $flightAttributes = [
            'dep' => $request->dep,
            'arr' => $request->arr,
            'route' => $request->route,
            'oceanicFL' => $request->oceanicFL,
            'oceanicTrack' => $request->oceanicTrack,
        ];

        if ($request->ctot) {
            $flightAttributes['ctot'] = Carbon::createFromFormat('Y-m-d H:i',
                $booking->event->startEvent->toDateString().' '.$request->ctot);
        }

        if ($request->eta) {
            $flightAttributes['eta'] = Carbon::createFromFormat('Y-m-d H:i',
                $booking->event->startEvent->toDateString().' '.$request->eta);
        }

        $flight->fill($flightAttributes);

        if ($shouldSendEmail) {
            $changes = collect();
            foreach ($booking->getDirty() as $key => $value) {
                $changes->push(
                    ['name' => $key, 'old' => $booking->getOriginal($key), 'new' => $value]
                );
            }
            foreach ($flight->getDirty() as $key => $value) {
                $changes->push(
                    ['name' => $key, 'old' => $flight->getOriginal($key), 'new' => $value]
                );
            }
            if (!empty($request->message)) {
                $changes->push(
                    ['name' => 'message', 'new' => $request->message]
                );
            }
        }

        $booking->save();
        $flight->save();
        $message = 'Booking has been changed!';
        if ($shouldSendEmail) {
            $booking->user->notify(new BookingChanged($booking, $changes));
            $message .= ' A E-mail has also been sent to the person that booked.';
        }
        flashMessage('success', 'Booking changed', $message);
        return redirect(route('bookings.event.index', $booking->event));
    }

    /**
     * Remove the specified booking from storage.
     *
     * @param  Booking  $booking
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Booking $booking)
    {
        if ($booking->event->endEvent >= now()) {
            $booking->delete();
            $message = 'Booking has been deleted.';
            if (!empty($booking->user)) {
                $message .= ' A E-mail has also been sent to the person that booked.';
                $booking->user->notify(new BookingDeleted($booking->event));
            }
            flashMessage('success', 'Booking deleted!', $message);
            return redirect(route('bookings.event.index', $booking->event));
        }
        flashMessage('danger', 'Nope!', 'You cannot delete a booking after the event ended');
        return back();
    }

    /**
     * Exports all active bookings to a .csv file
     *
     * @param  Event  $event
     * @return string|\Symfony\Component\HttpFoundation\StreamedResponse
     * @throws \Box\Spout\Common\Exception\IOException
     * @throws \Box\Spout\Common\Exception\InvalidArgumentException
     * @throws \Box\Spout\Common\Exception\UnsupportedTypeException
     * @throws \Box\Spout\Writer\Exception\WriterNotOpenedException
     */
    public function export(Event $event, Request $request)
    {
        activity()
            ->by(auth()->user())
            ->on($event)
            ->log('Export triggered');
        $bookings = Booking::where('event_id', $event->id)
            ->where('status', BookingStatus::BOOKED)
            ->get();
        if ($event->event_type_id == EventType::MULTIFLIGHTS) {
            if ($request->vacc) {
                return (new FastExcel($bookings))->withoutHeaders()->download('bookings.csv', function ($booking) {
                    /* @var Booking $booking */
                    /* @var Flight $flight1 */
                    /* @var Flight $flight2 */
                    $flight1 = $booking->flights()->first();
                    $flight2 = $booking->flights()->whereKeyNot($flight1->id)->first();
                    return [
                        $booking->user->full_name,
                        $booking->user_id,
                        $booking->user->email,
                        $booking->callsign,
                        $flight1->airportDep->icao,

resources/views/booking/overview.blade.php
@extends('layouts.app')

@section('content')
    @if($event)
        <h3>{{ $event->name }} | {{ $filter ? ucfirst($filter) : 'Slot Table' }}</h3>
        <hr>
        <p>
            @if($event->hasOrderButtons())
                <a href="{{ route('bookings.event.index',$event) }}"
                   class="btn btn-{{ url()->current() === route('bookings.event.index', $event) || url()->current() === route('bookings.event.index', $event) ? 'success' : 'primary' }}">Show
                    All</a>&nbsp;
                <a href="{{ route('bookings.event.index',$event) }}/departures"
                   class="btn btn-{{ url()->current() === route('bookings.event.index', $event) . '/departures' ? 'success' : 'primary' }}">Show
                    Departures</a>&nbsp;
                <a href="{{ route('bookings.event.index',$event) }}/arrivals"
                   class="btn btn-{{ url()->current() === route('bookings.event.index', $event) . '/arrivals' ? 'success' : 'primary' }}">Show
                    Arrivals</a>&nbsp;
            @endif
            @if(auth()->check() && auth()->user()->isAdmin && $event->endBooking >= now())
                @push('scripts')
                    <script>
                        $('.delete-booking').on('click', function (e) {
                            e.preventDefault();
                            Swal.fire({
                                title: 'Are you sure',
                                text: 'Are you sure you want to remove this booking?',
                                icon: 'warning',
                                showCancelButton: true,
                            }).then((result) => {
                                if (result.value) {
                                    Swal.fire('Deleting booking...');
                                    Swal.showLoading();
                                    $(this).closest('form').submit();
                                }
                            });
                        });
                    </script>
                @endpush
                <a href="{{ route('admin.bookings.create',$event) }}" class="btn btn-primary"><i class="fa fa-plus"></i>
                    Add
                    Booking</a>&nbsp;
                <a href="{{ route('admin.bookings.create',$event) }}/bulk" class="btn btn-primary"><i
                        class="fa fa-plus"></i>
                    Add
                    Timeslots</a>&nbsp;
            @endif
        </p>
        @include('layouts.alert')
        @if($event->startBooking <= now() || auth()->check() && auth()->user()->isAdmin)
            Flights available: {{ $total - $booked }} / {{ $total }}
            <table class="table table-hover table-responsive">
                <thead>
                <tr>
                    <th scope="row">From</th>
                    <th scope="row">To</th>
                    @if($event->uses_times)
                        <th scope="row"><abbr title="Calculated Take Off Time">CTOT</abbr></th>
                        <th scope="row"><abbr title="Estimated Time of Arrival">ETA</abbr></th>
                    @endif
                    <th scope="row">Callsign</th>
                    <th scope="row">Aircraft</th>
                    <th scope="row">Book | Available until {{ $event->endBooking->format('d-m-Y H:i') }}z</th>
                    @if((auth()->check() && auth()->user()->isAdmin) && $event->endEvent >= now())
                        <th colspan="3" scope="row">Admin actions</th>
                    @endif
                </tr>
                </thead>
                @foreach($bookings as $booking)
                    @php($flight = $booking->flights->first())
                    {{-- @TODO Temp fix for events using filter buttons--}}
                    @if($flight)
                        {{--Check if flight belongs to the logged in user--}}
                        <tr class="{{ auth()->check() && $booking->user_id == auth()->id() ? 'table-active' : '' }}">
                            <td>
                                {!! $flight->airportDep->fullName !!}
                            </td>
                            <td>
                                {!! $flight->airportArr->fullName !!}
                            </td>
                            @if($booking->event->uses_times)
                                <td>
                                    {{ $flight->formattedCtot }}
                                </td>
                                <td>
                                    {{ $flight->formattedEta }}
                                </td>
                            @endif
                            <td class="{{ auth()->check() && auth()->user()->use_monospace_font ? 'text-monospace' : '' }}">{{ $booking->callsign }}</td>
                            <td class="{{ auth()->check() && auth()->user()->use_monospace_font ? 'text-monospace' : '' }}">{{ $booking->acType }}</td>
                            <td>
                                {{--Check if booking has been booked--}}
                                @if($booking->status === \App\Enums\BookingStatus::BOOKED)
                                    {{--Check if booking has been booked by current user--}}
                                    @if(auth()->check() && $booking->user_id == auth()->id())
                                        <a href="{{ route('bookings.show',$booking) }}" class="btn btn-info">My
                                            booking</a>
                                    @else
                                        <button class="btn btn-dark disabled">
                                            Booked [{{ $booking->user->id }}]
                                        </button>
                                    @endif

                                @elseif($booking->status === \App\Enums\BookingStatus::RESERVED)
                                    {{--Check if a booking has been reserved--}}
                                    @can('update', $booking)
                                        {{--Check if a booking has been reserved by current user--}}
                                        <a href="{{ route('bookings.edit',$booking) }}" class="btn btn-info">My
                                            Reservation</a>
                                    @else
                                        <button class="btn btn-dark disabled">
                                            Reserved {{auth()->check() && auth()->user()->isAdmin ? '['.$booking->user->pic .']' : ''}}</button>
                                    @endcan
                                @else
                                    @if(auth()->check())
                                        {{--Check if user is logged in--}}
                                        @if($booking->event->startBooking <= now() && $booking->event->endBooking >= now())
                                            {{--Check if user already has a booking--}}
                                            @if(($booking->event->multiple_bookings_allowed) || (!$booking->event->multiple_bookings_allowed && !auth()->user()->bookings->where('event_id',$event->id)->first()))
                                                {{--Check if user already has a booking, and only 1 is allowed--}}
                                                <a href="{{ route('bookings.edit', $booking) }}" class="btn btn-success">BOOK
                                                    NOW</a>
                                            @else
                                                <i class="text-danger">You already have a booking</i>
                                            @endif
                                        @else
                                            <button class="btn btn-danger">Not available</button>
                                        @endif
                                    @else
                                        <a href="{{ route('login', ['booking' => $booking]) }}" class="btn btn-info">Click here to
                                            login</a>
                                    @endif
                                @endif
                            </td>
                            @if((auth()->check() && auth()->user()->isAdmin) && ($event->endEvent >= now()))
                                <td><a href="{{ route('admin.bookings.edit', $booking) }}" class="btn btn-info"><i
                                            class="fa fa-edit"></i> Edit</a>
                                </td>
                                <td>
                                    <form action="{{ route('admin.bookings.destroy', $booking) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger delete-booking"><i class="fas fa-trash"></i> Delete
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    @if($booking->user_id)
                                        <a href="mailto:{{ $booking->user->email }}" style="color: white;">
                                            <button class="btn btn-info">
                                                <i class="fas fa-envelope"></i> Send E-mail [{{ $booking->user->email }}]
                                            </button>
                                        </a>
                                    @endif
                                </td>
                            @endif
                        </tr>
                    @endif
                @endforeach
            </table>
        @else
            <h3>Bookings will be available at <strong>{{ $event->startBooking->format('d-m-Y H:i') }}z</strong></h3><br>
        @endif
    @else
        Currently no events scheduled for booking.
    @endif
@endsection