routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('home');

Route::get('/login', 'Auth\LoginController@login')->name('login');
Route::get('/validate-login', 'Auth\LoginController@validateLogin');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Admin routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'auth.isAdmin'], function () {
    // Airports
    Route::get('airports/import', 'Airport\AirportAdminController@import')->name('admin.airports.import');
    Route::resource('airports', 'Airport\AirportAdminController');

    // AirportLinks
    Route::resource('airportLinks', 'AirportLink\AirportLinkAdminController')->except(['show']);

    // Faq
    Route::resource('faq', 'Faq\FaqAdminController')->except('show');
    Route::patch('faq/{faq}/toggle-event/{event}', 'Faq\FaqAdminController@toggleEvent')->name('faq.toggleEvent');

    // Event
    Route::resource('events', 'Event\EventAdminController');
    Route::get('{event}/email', 'Event\EventAdminController@sendEmailForm')->name('events.email.form');
    Route::patch('{event}/email', 'Event\EventAdminController@sendEmail')->name('events.email');
    Route::patch('{event}/email_final',
        'Event\EventAdminController@sendFinalInformationMail')->name('events.email.final');

    // Booking
    Route::resource('bookings', 'Booking\BookingAdminController')->except(['index', 'show']);
    Route::get('{event}/bookings/export/{vacc?}', 'Booking\BookingAdminController@export')->name('bookings.export');
    Route::get('{event}/bookings/create/{bulk?}', 'Booking\BookingAdminController@create')->name('bookings.create');
    Route::get('{event}/bookings/import', 'Booking\BookingAdminController@importForm')->name('bookings.importForm');
    Route::put('{event}/bookings/import', 'Booking\BookingAdminController@import')->name('bookings.import');
    Route::get('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssignForm')->name('bookings.autoAssignForm');
    Route::patch('{event}/bookings/auto-assign',
        'Booking\BookingAdminController@adminAutoAssign')->name('bookings.autoAssign');
    Route::get('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssignForm')->name('bookings.routeAssignForm');
    Route::patch('{event}/bookings/route-assign',
        'Booking\BookingAdminController@routeAssign')->name('bookings.routeAssign');
});

Route::resource('bookings', 'Booking\BookingController')->except(['create', 'edit', 'store', 'destroy']);
Route::get('/{event}/bookings/{filter?}', 'Booking\BookingController@index')->name('bookings.event.index');
Route::get('/bookings/{booking}/edit', 'Booking\BookingController@edit')
    ->middleware('auth.isLoggedIn')->name('bookings.edit');
Route::patch('/bookings/{booking}/cancel', 'Booking\BookingController@cancel')->name('bookings.cancel');

// Keeping this here for a while to prevent some 404's should people access /booking directly
Route::redirect('/booking', route('bookings.index'), 301);

Route::get('faq', 'Faq\FaqController')->name('faq');

Route::get('{event}', 'Event\EventController')->name('events.show');

Route::middleware('auth.isLoggedIn')->group(function () {
    Route::prefix('user')->name('user.')
        ->group(function () {
            Route::get('settings', 'User\UserController@showSettingsForm')->name('settings');
            Route::patch('settings', 'User\UserController@saveSettings')->name('saveSettings');
        });
});

app/Models/EventType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

/**
 * App\Models\EventType
 *
 * @property int $id
 * @property string $name
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\Activitylog\Models\Activity[] $activities
 * @property-read int|null $activities_count
 * @property-read \App\Models\Event $events
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\EventType newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\EventType newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\EventType query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\EventType whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\EventType whereName($value)
 * @mixin \Eloquent
 */
class EventType extends Model
{
    use LogsActivity;

    public $incrementing = false;
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;

    public function events()
    {
        return $this->belongsTo(Event::class, 'id');
    }
}

app/Http/Controllers/Event/EventAdminController.php
<?php

namespace App\Http\Controllers\Event;

use App\Enums\BookingStatus;
use App\Http\Controllers\AdminController;
use App\Http\Requests\Event\Admin\SendEmail;
use App\Http\Requests\Event\Admin\StoreEvent;
use App\Http\Requests\Event\Admin\UpdateEvent;
use App\Models\Airport;
use App\Models\Booking;
use App\Models\Event;
use App\Models\EventType;
use App\Models\User;
use App\Notifications\EventBulkEmail;
use App\Notifications\EventFinalInformation;
use App\Policies\EventPolicy;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Notification;

class EventAdminController extends AdminController
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->authorizeResource(EventPolicy::class, 'event');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::orderByDesc('startEvent')
            ->with('type')
            ->paginate();
        return view('event.admin.overview', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $event = new Event;
        $airports = Airport::orderBy('icao')->get();
        $eventTypes = EventType::all();
        return view('event.admin.form', compact('event', 'airports', 'eventTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreEvent  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEvent $request)
    {
        $event = new Event();
        $event->fill($request->only('is_online', 'show_on_homepage', 'name', 'event_type_id', 'import_only',
            'uses_times',
            'multiple_bookings_allowed', 'is_oceanic_event', 'dep', 'arr', 'image_url', 'description'));
        $event->fill([
            'startEvent' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEvent.' '.$request->timeBeginEvent),
            'endEvent' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEvent.' '.$request->timeEndEvent),
            'startBooking' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateBeginBooking.' '.$request->timeBeginBooking),
            'endBooking' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEndBooking.' '.$request->timeEndBooking),
        ])->save();

        flashMessage('success', 'Done', 'Event has been created!');
        return redirect(route('admin.events.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Event  $event
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Event $event)
    {
        return view('event.admin.show', compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        $airports = Airport::orderBy('icao')->get();
        $eventTypes = EventType::all();
        return view('event.admin.form', compact('event', 'airports', 'eventTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateEvent  $request
     * @param  Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEvent $request, Event $event)
    {
        $event->fill($request->only('is_online', 'show_on_homepage', 'name', 'event_type_id', 'import_only',
            'uses_times',
            'multiple_bookings_allowed', 'is_oceanic_event', 'dep', 'arr', 'image_url', 'description'));
        $event->fill([
            'startEvent' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEvent.' '.$request->timeBeginEvent),
            'endEvent' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEvent.' '.$request->timeEndEvent),
            'startBooking' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateBeginBooking.' '.$request->timeBeginBooking),
            'endBooking' => Carbon::createFromFormat('d-m-Y H:i',
                $request->dateEndBooking.' '.$request->timeEndBooking),
        ])->save();
        flashMessage('success', 'Done', 'Event has been updated!');
        return redirect(route('admin.events.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Event  $event
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Event $event)
    {
        if ($event->startEvent > now()) {
            $event->delete();
            flashMessage('success', 'Done', $event->name.' has been deleted!');
            return redirect()->back();
        } else {
            flashMessage('danger', 'Nope!', 'You cannot remove a event after it has begun!');
            return redirect()->back();
        }
    }

    /**
     * Opens form to either use sendEmail() or sendFinalInformationMail()
     *
     * @param  Event  $event
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function sendEmailForm(Event $event)
    {
        return view('event.admin.sendEmail', compact('event'));
    }

    /**
     * Sends E-mail to all users who booked a flight as a notification by administrators.
     *
     * @param  SendEmail  $request
     * @param  Event  $event
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function sendEmail(SendEmail $request, Event $event)
    {
        if ($request->testmode) {
            Notification::send(auth()->user(), new EventBulkEmail($event, $request->subject, $request->message));
            activity()
                ->by(auth()->user())
                ->on($event)
                ->withProperties(
                    [
                        'subject' => $request->subject,
                        'message' => $request->message,
                    ]
                )
                ->log('Bulk E-mail test performed');
            return response()->json(['success' => 'Email has been sent to yourself']);
        } else {
            $bookings = Booking::where('event_id', $event->id)
                ->where('status', BookingStatus::BOOKED)
                ->get();
            $users = User::find($bookings->pluck('user_id'));
            Notification::send($users, new EventBulkEmail($event, $request->subject, $request->message));
            $count = $users->count();

            flashMessage('success', 'Done', 'Bulk E-mail has been sent to '.$count.' people!');
            activity()
                ->by(auth()->user())
                ->on($event)
                ->withProperties(
                    [
                        'subject' => $request->subject,
                        'message' => $request->message,
                        'count' => $count,
                    ]
                )
                ->log('Bulk E-mail');
        }
        return redirect(route('admin.events.index'));
    }

    /**
     * Sends E-mail to all users who booked a flight the final information.
     *
     * @param  Event  $event
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function sendFinalInformationMail(Request $request, Event $event)
    {
        $bookings = Booking::where('event_id', $event->id)
            ->where('status', BookingStatus::BOOKED)
            ->get();

        if ($request->testmode) {
            $booking = $bookings->random();
            Notification::send(auth()->user(), new EventFinalInformation($booking));

            activity()
                ->by(auth()->user())
                ->on($event)
                ->withProperties(
                    [
                        'booking' => $booking,
                    ]
                )
                ->log('Final Information E-mail test performed');
            return response()->json(['success' => 'Email has been sent to yourself']);
        } else {
            $count = $bookings->count();
            $countSkipped = 0;
            $now = now();
            foreach ($bookings as $booking) {
                $shouldSend = false;
                if (!$booking->has_received_final_information_email || $request->forceSend) {
                    $shouldSend = true;
                }

                // @TODO Maybe better in a Event/Listener?
                if ($shouldSend) {
                    $booking->user->notify(new EventFinalInformation($booking));
                    $booking->update(['final_information_email_sent_at' => $now]);
                } else {
                    $count--;
                    $countSkipped++;
                }
            }
            $message = 'Final Information has been sent to '.$count.' people!';
            if ($countSkipped != 0) {
                $message .= ' However, ' . $countSkipped . ' where skipped, because they already received one';
            }
            flashMessage('success', 'Done', $message);
            activity()
                ->by(auth()->user())
                ->on($event)
                ->withProperty('count', $count)
                ->log('Final Information E-mail');
        }
        return redirect(route('admin.events.index'));
    }
}

app/Http/Controllers/Event/EventController.php
<?php

namespace App\Http\Controllers\Event;

use App\Http\Controllers\Controller;
use App\Models\Event;

class EventController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  Event  $event
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Event $event)
    {
        return view('event.show', compact('event'));
    }
}

resources/views/event/admin/autoAssign.blade.php
@extends('layouts.app')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @include('layouts.alert')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $event->name }} | Auto-Assign FL / Route</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.bookings.autoAssign',$event) }}">
                        @csrf
                        @method('PATCH')

                        {{--Track #1--}}
                        <div class="form-group row">
                            <label for="oceanicTrack1" class="col-md-4 col-form-label text-md-right">Track #1</label>

                            <div class="col-md-6">
                                <input id="oceanicTrack1" type="text"
                                       class="form-control{{ $errors->has('oceanicTrack1') ? ' is-invalid' : '' }}"
                                       name="oceanicTrack1"
                                       value="{{ old('oceanicTrack') }}" max="2">

                                @if ($errors->has('oceanicTrack'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('oceanicTrack1') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Route #1--}}
                        <div class="form-group row">
                            <label for="route1" class="col-md-4 col-form-label text-md-right">Route #1</label>

                            <div class="col-md-6">
                                <textarea class="form-control" id="route1"
                                          name="route1">{{ old('route1') }}</textarea>

                                @if ($errors->has('route'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('route1') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Track #2--}}
                        <div class="form-group row">
                            <label for="oceanicTrack2" class="col-md-4 col-form-label text-md-right">Track #2</label>

                            <div class="col-md-6">
                                <input id="oceanicTrack2" type="text"
                                       class="form-control{{ $errors->has('oceanicTrack1') ? ' is-invalid' : '' }}"
                                       name="oceanicTrack2"
                                       value="{{ old('oceanicTrack2') }}" max="2">

                                @if ($errors->has('oceanicTrack'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('oceanicTrack2') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Route #2--}}
                        <div class="form-group row">
                            <label for="route2" class="col-md-4 col-form-label text-md-right">Route #2</label>

                            <div class="col-md-6">
                                <textarea class="form-control" id="route1"
                                          name="route2">{{ old('route2') }}</textarea>

                                @if ($errors->has('route2'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('route2') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Max FL--}}
                        <div class="form-group row">
                            <label for="minFL" class="col-md-4 col-form-label text-md-right">Minimum Oceanic Entry
                                FL</label>

                            <div class="col-md-6">
                                <input id="minFL" type="text"
                                       class="form-control{{ $errors->has('minFL') ? ' is-invalid' : '' }}"
                                       name="minFL"
                                       value="{{ old('minFL', 320) }}" max="3">

                                @if ($errors->has('minFL'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('minFL') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Max FL--}}
                        <div class="form-group row">
                            <label for="maxFL" class="col-md-4 col-form-label text-md-right">Maximum Oceanic Entry
                                FL</label>

                            <div class="col-md-6">
                                <input id="maxFL" type="text"
                                       class="form-control{{ $errors->has('maxFL') ? ' is-invalid' : '' }}"
                                       name="maxFL"
                                       value="{{ old('maxFL',380) }}" max="3">

                                @if ($errors->has('minFL'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('maxFL') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--Assign All Flights--}}
                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="custom-control custom-checkbox">
                                    <input class="custom-control-input" id="checkAssignAllFlights" type="checkbox"
                                           name="checkAssignAllFlights">
                                    <label class="custom-control-label" for="checkAssignAllFlights"><abbr
                                            title="When enabled, all flights, regardless of being booked will be auto-assigned">Auto-assign
                                            all flights?</abbr></label>
                                </div>
                            </div>
                        </div>

                        {{--Auto-Assign FL / Route--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-check"></i> Auto-Assign FL / Route
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/event/admin/import.blade.php
@extends('layouts.app')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @include('layouts.alert')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $event->name }} | Import</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.bookings.import',$event) }}"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        {{--File--}}
                        <div class="form-group row">

                            <div class="col-md-4 col-form-label text-md-right"></div>
                            <div class="col-md-6">
                                <input type="file" class="form-control-file" id="file" name="file">

                                @if ($errors->has('file'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('file') }}</strong>
                                    </span>
                                @endif

                            </div>
                        </div>

                        <div class="form-group row">

                            <div class="col-md-4 text-md-right">
                                <label for="ctot"> Headers in <strong>bold</strong> are mandatory</label>
                                <a class="btn btn-secondary" href="{{ url('import_template.xlsx') }}">
                                    <i class="fas fa-file-excel"></i> Download template
                                </a>
                            </div>

                            <div class="col-md-8">
                                <div class="form-control-plaintext">
                                    @if($event->event_type_id == \App\Enums\EventType::MULTIFLIGHTS)
                                        <strong><abbr title="[hh:mm]">CTOT 1</abbr></strong> - <strong><abbr title="[ICAO]">Airport 1</abbr></strong> -
                                        <strong><abbr title="[hh:mm]">CTOT 2</abbr></strong> - <strong><abbr title="[ICAO]">Airport 2</abbr></strong> -
                                        <strong><abbr title="[ICAO]">Airport 3</abbr></strong>
                                    @else
                                        Call Sign | <strong><abbr title="[ICAO]">Origin</abbr></strong> |
                                        <strong><abbr title="[ICAO]">Destination</abbr></strong> |
                                        <abbr title="[hh:mm]">EOBT</abbr> | <abbr title="[hh:mm]">ETA</abbr> |
                                        <abbr title="[ICAO]">Aircraft Type</abbr> | Route

                                    @endif
                                </div>
                            </div>
                        </div>

                        {{--Import--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    <i class="fas fa-check"></i> Import
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/event/admin/overview.blade.php
@extends('layouts.app')

@section('content')
    <h3>Events Overview</h3>
    <hr>
    <p><a href="{{ route('admin.events.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add new Event</a>
    </p>
    @include('layouts.alert')
    @push('scripts')
        <script>
            $('.delete-event').on('click', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Are you sure',
                    text: 'Are you sure you want to remove this event?',
                    icon: 'warning',
                    showCancelButton: true,
                }).then((result) => {
                    if (result.value) {
                        Swal.fire('Deleting event...');
                        Swal.showLoading();
                        $(this).closest('form').submit();
                    }
                });
            });
        </script>
    @endpush
    <table class="table table-hover table-responsive">
        <thead>
        <tr>
            <th scope="row">ID</th>
            <th scope="row">Name</th>
            <th scope="row">Type</th>
            <th scope="row">Date</th>
            <th scope="row">Start</th>
            <th scope="row">End</th>
            <th scope="row">Actions</th>
        </tr>
        </thead>
        @forelse($events as $event)
            @if($event->endEvent < now())
                <tr class="table-active">
            @else
                <tr>
                    @endif
                    <td>{{ $event->id }}</td>
                    <td><a href="{{ route('admin.events.show', $event) }}">{{ $event->name }}</a>
                    </td>
                    <td>{{ $event->type->name }}</td>
                    <td>{{ $event->startEvent->format('d-m-Y') }}</td>
                    <td>{{ $event->startEvent->format('Hi') }}z</td>
                    <td>{{ $event->endEvent->format('Hi') }}z</td>
                    <td>
                        <a href="{{ route('admin.events.edit',$event) }}" role="button" class="btn btn-primary"><i
                                class="fa fa-edit"></i> Edit</a>&nbsp;
                        @if($event->endEvent > now())
                            <a href="{{ route('admin.bookings.importForm',$event) }}" class="btn btn-success"><i
                                    class="fa fa-file-import"></i> Import data</a>&nbsp;
                            <a href="{{ route('admin.bookings.create', $event) }}/bulk" class="btn btn-primary"><i
                                    class="fa fa-plus"></i> Add Timeslots</a>&nbsp;
                            @if($event->is_oceanic_event)
                                <a href="{{ route('admin.bookings.autoAssignForm',$event) }}" class="btn btn-primary">
                                    Auto Assign FL / Route</a>&nbsp;
                            @endif
                        @endif
                        <a href="{{ route('admin.events.email.form',$event) }}" class="btn btn-primary"><i
                                class="fa fa-envelope"></i> Send mail to all</a>&nbsp;

                        <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-file-export"></i> Export</button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('admin.bookings.export',$event) }}">Excluding emails</a>
                            @if($event->event_type_id == \App\Enums\EventType::MULTIFLIGHTS)
                                <a class="dropdown-item" href="{{ route('admin.bookings.export',[$event, 'vacc']) }}">Including emails</a>
                            @endif
                        </div>

                        @if($event->event_type_id == \App\Enums\EventType::MULTIFLIGHTS)
                            <a href="{{ route('admin.bookings.routeAssignForm', $event) }}" class="btn btn-primary"><i
                                    class="fa fa-edit"></i> Assign Routes</a>&nbsp;
                        @endif
                        @if($event->startEvent > now())
                            <form action="{{ route('admin.events.destroy', $event) }}" method="post" style="margin-top: 10px;">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger delete-event">Delete Event</button>
                            </form>
                        @endif
                    </td>
                </tr>
                @empty
                    @php
                        flashMessage('info', 'No events found', 'No events are in the system, consider adding one, using the button above');
                    @endphp
                    @include('layouts.alert')
                @endforelse
                {{ $events->links() }}
    </table>
    {{ $events->links() }}
@endsection